services:
  whatsapp-ha-bridge:
    image: ghcr.io/mirci212/whatsapp-bridge-homeassisant:latest
    container_name: whatsapp-bridge-homeassisant
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - TZ=Europe/Vienna
      - PORT=3000
      - HA_URL=http://192.168.0.2:8123
      - HA_TOKEN=dein_long_lived_access_token
      - CONVERSATION_AGENT=conversation.gemini_live
      - ALLOWED_USERS=43***:Marco,43****:Brigitte
      - STT_ENGINE=stt.faster_whisper
      - TTS_ENGINE=tts.piper
    volumes:
      - ha_bridge_auth:/app/auth_info_baileys

volumes:
  ha_bridge_auth: